// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAoPO5WAKSMajK6lwyyuS-YDjyRiC-sdI',
    appId: '1:536739893720:web:cbe0e56d317901f64d62ad',
    messagingSenderId: '536739893720',
    projectId: 'betagric-a3f86',
    authDomain: 'betagric-a3f86.firebaseapp.com',
    databaseURL: 'https://betagric-a3f86-default-rtdb.firebaseio.com',
    storageBucket: 'betagric-a3f86.appspot.com',
    measurementId: 'G-4DVW9LVBTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFXjcmjFaxHwKKGtcz-YARLnIijyjlSD4',
    appId: '1:536739893720:android:8e163b7075b268064d62ad',
    messagingSenderId: '536739893720',
    projectId: 'betagric-a3f86',
    databaseURL: 'https://betagric-a3f86-default-rtdb.firebaseio.com',
    storageBucket: 'betagric-a3f86.appspot.com',
  );
}
